# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Homepage (reinhart1010.id)
    url: https://reinhart1010.id
  - name: BINUSToday
    url: https://binustoday.reinhart1010.id
  - name: BINUSMAYA Down
    url: https://binusmayadown.reinhart1010.id
  - name: Food Navigator
    url: https://reinhart1010.github.io/foodnavigator
  - name: HAM Homepage
    url: https://ham.reinhart1010.id
  - name: Nix
    url: https://nix.reinhart1010.id
  - name: roothouse-0
    url: http://192.168.10.10
  - name: roothouse-1
    url: http://192.168.10.11
  - name: roothouse-2
    url: http://192.168.10.12
  - name: roothouse-3
    url: http://192.168.10.13

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.reinhart1010.id
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Reinhart Previano K.
  introTitle: "Server status for **reinhart1010.id**, the **roothouse**, and beyond."
  introMessage: By the way, did you know that we also bought **alterine0101.id**? All the **root**est stories are coming there soon.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/10 * * * *"

runner: [self-hosted, can-fetch]
user-agent: roothouse/1.0 (+https://bots.reinhart1010.id)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
