# Change these first
owner: alterine0101 # Your GitHub organization or username, where this repository lives
repo: roothouse-status # The name of this repository

sites:
  - name: Homepage (reinhart1010.id)
    url: https://reinhart1010.id
  - name: BINUSToday
    url: https://binustoday.reinhart1010.id
  - name: BINUSMAYA Down
    url: https://binusmayadown.reinhart1010.id
  - name: BOTS Misskey Instance
    url: https://bots.reinhart1010.id
  - name: Caps Landing Page
    url: https://caps.reinhart1010.id
  - name: Doa Prophetic Landing Page
    url: https://doaprophetic.reinhart1010.id
  - name: File Sharing Service (files.reinhart1010.id)
    url: https://files.reinhart1010.id
  - name: Food Navigator
    url: https://reinhart1010.github.io/foodnavigator
  - name: GMS MSJ Admin Bot (@caps_gms_msj_bot)
    url: https://rhstatus-proxy.alterine0101.id/?deviceId=gms-msj-telegram-bot
  - name: GMS MSJ Admin Bot Documentation
    url: https://gms-msj-telegram-bot.reinhart1010.id/
  - name: Hackapedia
    url: https://hackapedia.reinhart1010.id
  - name: HAM Homepage
    url: https://ham.reinhart1010.id
  - name: Jackpot GBK
    url: https://reinhart1010.github.io/jackpotgbk
  - name: Nix
    url: https://nix.reinhart1010.id
  - name: Reinhart Maps
    url: https://maps.reinhart1010.id
  - name: Shortlink Service (share.reinhart1010.id)
    url: https://share.reinhart1010.id
  - name: Webmail Service
    url: https://webmail.reinhart1010.id
#   - name: roothouse-0
#     url: https://rhstatus-proxy.alterine0101.id/?deviceId=roothouse-0
#   - name: roothouse-1
#     url: https://rhstatus-proxy.alterine0101.id/?deviceId=roothouse-1
#   - name: roothouse-2
#     url: https://rhstatus-proxy.alterine0101.id/?deviceId=roothouse-2
#   - name: roothouse-3
#     url: https://rhstatus-proxy.alterine0101.id/?deviceId=roothouse-3

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.reinhart1010.id
  # baseUrl: /your-repo-name
  logoUrl: https://reinhart1010.id/wp-content/uploads/2022/06/cropped-IMG_20220618_124332_108-1.png
  name: Shift
  introTitle: "Server status for **reinhart1010.id**, the **roothouse**, and beyond."
  introMessage: By the way, did you know that we also have [a dedicated website](https://binusmayadown.reinhart1010.id) to check if BINUS University's main servers are down, too?
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/10 * * * *"

user-agent: roothouse/1.0 (+https://bots.reinhart1010.id)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
